package com.discord.api.guild;

public enum GuildFeature {
    VIP_REGIONS,
    INVITE_SPLASH,
    VANITY_URL,
    VERIFIED,
    MORE_EMOJI,
    BANNER,
    PARTNERED,
    COMMERCE,
    NEWS,
    DISCOVERABLE,
    FEATURABLE,
    ANIMATED_ICON,
    COMMUNITY,
    MEMBER_VERIFICATION_GATE_ENABLED,
    PREVIEW_ENABLED,
    CREATOR_MONETIZABLE,
    CREATOR_MONETIZABLE_DISABLED,
    ROLE_SUBSCRIPTIONS_ENABLED,
    ROLE_SUBSCRIPTIONS_AVAILABLE_FOR_PURCHASE,
    THREAD_DEFAULT_AUTO_ARCHIVE_DURATION,
    HUB,
    THREADS_ENABLED,
    PRIVATE_THREADS,
    NEW_THREAD_PERMISSIONS,
    ROLE_ICONS,
    ANIMATED_BANNER,
    TEXT_IN_VOICE_ENABLED,
    HAS_DIRECTORY_ENTRY,
    BOOSTING_TIERS_EXPERIMENT_SMALL_GUILD,
    BOOSTING_TIERS_EXPERIMENT_MEDIUM_GUILD,

    // New
    MEMBER_VERIFICATION_MANUAL_APPROVAL
}